name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker buildx build --pull --tag containerd-registry .
      - run: |
          sudo ctr version
          test -S /run/containerd/containerd.sock
          docker run -dit --name containerd-registry --mount type=bind,src=/run/containerd/containerd.sock,dst=/run/containerd/containerd.sock,ro --publish 5000:5000 containerd-registry
      - run: sudo ctr content fetch docker.io/tianon/true:oci
      - run: docker run --rm localhost:5000/docker.io/tianon/true:oci
